id: 32b530fdea9a420d859f4120144b6ee0
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_736-The_Dharani_of_Parnasavari-v2
  language: en
  author: ''
  volume: {}
